export const ROUTES = {
    DASHBOARD: "/",
    MANAGE_USER: "user",
    // MANAGE_Reported_User: "reported-user",
    // ADD_TOPICS: "add-topics",
    // UPDATE_TOPICS: "update-topics",
    UPDATE_ADMIN: "update-admin",
    LOGIN: "login",
    MANAGE_TOPICS: "manage-topics",
    SERVICES: "services",
    PROFILE: "profile",
    FAQS: "faqs",
    ADMIN_MANAGE: "admin",
    ADD_ADMIN: "add-admin",
    ADD_HOSPITAL: 'add-hospital',
    UPDATE_HOSPITAL: 'update-hospital',
    MANAGE_HOSPITAL: 'manage-hospital',
    MANAGE_USER: 'manage-user',
    RECEPTIONIST: 'receptionist',
    ADD_DOCTOR: 'add-doctor',
    MANAGE_DOCTOR: 'manage-doctor',
    UPDATE_DOCTOR: 'update-doctor',
    ADD_RECEPTION: 'add-reception',
    MANAGE_RECEPTION: 'manage-reception',
    UPDATE_RECEPTION: 'update-reception',
    ALL_PATIENTS: 'patients',
}
